In [ ]:
# CREATING NUMPY/ ND- ARRAYS

import numpy as np

# method 1 : Using np.array()
arr1 = np.array([1,2,3,4,5])
print(arr1)
type(arr1)                                   # type of array
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

# method:2 Using np.zeros/empty/ones/random()
arr4 = np.zeros([2,3])                       # (rows, columns)
print(arr4)
arr5 = np.ones([3,3])
print(arr5)
arr6 = np.empty([2,3])
print(arr6)

# method:3 Using identity()
arr7 = np.identity(5)                        # identity matrix of order 5 x 5
print(arr7)
arr8 = np.identity(3)                        # identity matrix of order 3 x 3
print(arr8)

# method:4 Using arange()
arr9 = np.arange(10)                         # generate an array in the range
print(arr9)
arr10 = np.arange(5,15)                      # endpoint not included
print(arr10)
arr11 = np.arange(1,11,2)                    # skips one element, jump 2
print(arr11)

# method:5 Using linspace()
arr12 = np.linspace(10,20,10)
print(arr12)

# method:6 Using copy()
arr13 = arr10.copy()
print(arr13)

In [ ]:
# NUMPY PROPERTIES AND ATTRIBUTES

# 1. Shape (order of matrix)
print(arr1)
print(arr1.shape)
print(arr2)
print(arr2.shape)

# shape of 3D matrix
arr = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(arr)
print(arr.shape)                                        # 2 matrices of 2 x 2 order

# 2. ndim (dimension of a matrix)
print(arr.ndim)
print(arr2.ndim)
print(arr1.ndim)

# 3. size
print(arr1.size)
print(arr2.size)
print(arr.size)

# 4. itemsize
a = np.array([1.3])
print(a.itemsize)


# 5. Dtype                        # data type (bits)
b = np.array([[1,2],[3,4]])
print(b.dtype)
print(a.dtype)

# 6. asType (Type casting)
a.astype("int")
print(a.astype("int"))           # type cast float array to int array



In [ ]:
# LISTS VS ARRAYS

# 1. Numpy array stores less moemory than python lists

import sys

listA = range(100)
arrA = np.arange(100)

print(sys.getsizeof(87)*len(listA))          # 2800 bytes
print(arrA.itemsize*arrA.size)               # 800 bytes

# 2. Numpy arrays are faster

import time
import numpy as np

x = range(100000000)
y = range(100000000, 200000000)

start_time = time.time()

c = [ x + y for x,y in zip(x,y)]

print("Time of execution: ", time.time() - start_time, "sec")

d = np.arange(100000000)
e = np.arange(100000000,200000000)

starting = time.time()

c = [d + e]

print("Time of execution:", time.time() - starting, "sec")

# 3. Iteration, indexing and slicing

a1 = np.arange(24).reshape(6,4)        # reshaping the arrays
print(a1)

a2 = np.array([1,2,3,4,5])

# indexing
print(a2)
print(a2[3])

# slicing
print(a2[2:4])
print(a2[-3:-1])
print(a1)
print(a1[2])                         # row of a 2D array

print(a1[1:3])
print(a1[-6:-3])
print(a1[:, 2])                      # columns of a 2D array
print(a1[:,1:3])                     # 2 columns
print(a1[2:4, 1:3])
print(a1[4:5, 2:3])

# iteration
for i in a1:
  print(i)
for i in np.nditer(a1):
  print(i)

In [ ]:
# NUMPY OPERATIONS

import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

# arithemetic operations
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 + arr2)
print(arr1 / arr2)
print(arr1 * 2)
print(arr1 > 3)              # checks for all elements

# matrix multiplication
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
print(arr3.dot(arr4))
print(arr1.dot(arr2))             # 1 x 5 mul 1 x 5 --> 1 x 1

# max & min
print(arr4)
print(arr4.max())
print(arr4.min(axis = 0))        # har column ka min
print(arr4.max(axis = 1))        # har row ka max

sum
print(arr4.sum())                # sum of all entries
print(arr4.sum(axis = 0))        # column wise sum
print(arr4.sum(axis = 1))        # row wise sum

# mean
print(arr4.mean())
# (can be done axis wise)

# median
print(np.median(arr4))            # static function

# std (standard deviation)
print(arr4.std())

# trigonometric functions
print(np.sin(arr4))               # sin of all elements
print(np.tan(arr4))
print(np.cos(arr4))

# exponent and log
print(np.exp(arr4))
print(np.log(arr4))


In [ ]:
# RESHAPING NUMPY ARRAYS

import numpy as np

# # 1. Ravel - Converting nD arrays into 1D
# arr4 = np.arange(6,12).reshape(3,2)
# print(arr4)
# print(arr4.ravel())

# # 2. Transpose
# print(arr4.transpose())

# 3. Stacking - combining two arrays
arr5 = np.arange(20,26).reshape(3,2)
arr6 = np.arange(12,18).reshape(3,2)
print("\n", arr5)
print("\n", arr6)
# print("\n",np.hstack((arr5,arr6)))              # horizontal stack
# print("\n",np.vstack((arr5,arr6)))              # verticle stack

# 4. Splitting
print("\n", np.hsplit(arr5, 2))
print("\n", np.vsplit(arr5, 3))

In [ ]:
# FANCY INDEXING IN NUMPY

import numpy as np

arr = np.arange(24).reshape(6,4)
print(arr)
print(arr[[0,2,4]])               # any n number of row indexes

In [ ]:
# INDEXING USING BOOLEAN ARRAYS

import numpy as np

# random array
arr = np.random.randint(low = 1, high = 100, size = 20).reshape(4,5)
print(arr)
print(arr[0][1])

# conditional indexing - using boolean arrays
print(arr>50)                                   # true false array
print(arr[arr > 50])                            # returns the values which are > 50
print(arr[(arr % 2 == 0) & (arr > 50)])
arr[(arr % 2 == 0) & (arr > 50)] = 0            # set these elements to 0
print(arr)

In [ ]:
# PLOTTING GRAPHS USING NUMPY

import numpy as np

x = np.linspace(-40,40,100)
print(x.size)
y = np.sin(x)
print(y.size)

import matplotlib.pyplot as plt
%matplotlib inline

plt.plot(x,y)
y = x*x + 2*x + 6
plt.plot(x,y)
y = x*x*x
plt.plot(x,y)

In [69]:
# BROADCASTING - arithmetic operations on dissimilar arrays

import numpy as np

a1 = np.arange(10).reshape(5,2)
a2 = np.arange(10,20).reshape(5,2)
print(a1 + a2)

a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)
print(a3 + a4)                    # broadcasting


a3 = np.arange(9).reshape(1,4)
a4 = np.arange(3).reshape(4,3)
print(a3 + a4)                    # error


a5 = np.arange(4).reshape(1,4)
a6 = np.arange(4).reshape(4,1)
print(a5 + a6)

a7 = np.arange(1).reshape(1,1)
a8 = np.arange(4).reshape(4,1)
print(a7 + a8)

[[0]
 [1]
 [2]
 [3]]


In [109]:
# NUMPY FUNCTIONS

import numpy as np

np.random.random()                     # any random value

np.random.seed(1)                      # same random value each time
np.random.random()

np.random.uniform(3,10)                # a random value in a range

np.random.uniform(1,100,10)            # another parameter - size

np.random.uniform(1,100,10).reshape(2,5)   # 2D array

np.random.randint(1,10)                 # int values
np.random.randint(1,10,5)               # int values with a size
np.random.randint(1,10,15).reshape(5,3)   # 2d array

# index of max/min value
a = np.random.randint(1,50,5)
print(a)
print(np.argmax(a))
print(np.argmin(a))


print(a[a%2!=0])
a[a % 2 !=0] = 0
print(a)

np.where(a % 2 != 0 , -1, a)
a

# sort
print(np.sort(a))
# percentile
print(np.percentile(a,100))

[16  1  5 26 48]
[ 1  5 16 26 48]
47.824
